version: '3.1'

services:
  db:
    build: .
    container_name: meu_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meubanco
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
